# Generated by Django 2.2.28 on 2024-05-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='images/rydz.jpg', null=True, upload_to='images/'),
        ),
    ]
